baseURL = 'https://fireship.io/'
languageCode = 'en-us'
title = 'Fireship'
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params]
mainSections = ["lessons", "snippets"]

[params.algolia]
vars = ["title", "description", "summary", "date", "publishdate", "lastmod", "permalink"]
params = ["tags"]

[params.seoTitles]
  [params.seoTitles.contributors]
    suffix = " - Contributors | Fireship.io"
  [params.seoTitles.courses]
    prefix = "Learn "
    suffix = " Online Course | Fireship.io"
  [params.seoTitles.lessons]
    prefix = "Tutorial: "
    suffix = " | Fireship.io"
  [params.seoTitles.tags]
    suffix = " Tags | Fireship.io"

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4