name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master

env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
  ALGOLIA_APP_ID: 05VYZFXKNM 
  ALGOLIA_ADMIN_KEY: ${{secrets.ALGOLIA_ADMIN_KEY}}
  ALGOLIA_INDEX_NAME: content 
  ALGOLIA_INDEX_FILE: public/algolia.json
  HUGO_SALT: ${{secrets.HUGO_SALT}}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true
      - run: npm ci
      - run: npm run build
      - run: npm run algolia
      - run: npm run deploy
